### ISSUE TITLE
No such module 'FSKit'

### ISSUE THREAD

**Issue by slonopotamus** [KhaosT/FSKitSample#1]
I am trying to compile this software using Xcode 16.0 on macOS 15.0, but getting `No such module 'FSKit'` error on `import FSKit` line in `FSExpExtension.swift`. Do I need to perform some additional actions so that FSKit becomes available?

**Comment by KhaosT** [comment]
Apple took out FSKit from Xcode 16 GM. You can try using the Xcode 16.1 beta to build this.

**Comment by slonopotamus** [comment]
Thanks, FSKit module does exist in 16.1 beta

**Comment by slonopotamus** [comment]
And they removed it again in XCode 16.1 RC 1 :(

**Comment by yujinqiu** [comment]
FSKit module does exist in Xcode 16.2  :-(

**Comment by slonopotamus** [comment]
In 16.2 situation is the same. Apple adds it in betas, but removes from RC and release.

**Comment by KhaosT** [comment]
Guess they are having a hard time to ship this 🙃

**Comment by johnspurlock** [comment]
Is it back and working in the 16.3 betas?
